// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/assets/scss/main.scss";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Preloader from "@/components/Preloader"; // Add this import
import 'animate.css';
import Hero from "@/components/Hero";
import BackToTop from "@/components/BackToTop";
import MouseCursor from "@/components/MouseCursor";
import Offcanvas from "@/components/Offcanvas";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable}`}
            suppressHydrationWarning={true}
        >
        <Preloader />
        <BackToTop />
        <MouseCursor />
        <Offcanvas />
        <Header />
        {children}
        <Footer />
        </body>
        </html>
    );
}